Failed to complete cronjob at ('* * * * *', 'auctions.cron.closeoutExpiredListings', '>> /home/miles/webdev/cs50-py-ja/commerce/auctions/cron.log')
Traceback (most recent call last):
  File "/home/miles/webdev/cs50-py-ja/env/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/miles/webdev/cs50-py-ja/env/lib/python3.6/site-packages/django/db/backends/sqlite3/base.py", line 413, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: no such table: auctions_auctionlisting

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/miles/webdev/cs50-py-ja/env/lib/python3.6/site-packages/django_crontab/crontab.py", line 145, in run_job
    func(*job_args, **job_kwargs)
  File "/home/miles/webdev/cs50-py-ja/commerce/auctions/cron.py", line 9, in closeoutExpiredListings
    for listing in exp_listings:
  File "/home/miles/webdev/cs50-py-ja/env/lib/python3.6/site-packages/django/db/models/query.py", line 287, in __iter__
    self._fetch_all()
  File "/home/miles/webdev/cs50-py-ja/env/lib/python3.6/site-packages/django/db/models/query.py", line 1303, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/home/miles/webdev/cs50-py-ja/env/lib/python3.6/site-packages/django/db/models/query.py", line 53, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/home/miles/webdev/cs50-py-ja/env/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1156, in execute_sql
    cursor.execute(sql, params)
  File "/home/miles/webdev/cs50-py-ja/env/lib/python3.6/site-packages/django/db/backends/utils.py", line 98, in execute
    return super().execute(sql, params)
  File "/home/miles/webdev/cs50-py-ja/env/lib/python3.6/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/miles/webdev/cs50-py-ja/env/lib/python3.6/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/miles/webdev/cs50-py-ja/env/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/miles/webdev/cs50-py-ja/env/lib/python3.6/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/miles/webdev/cs50-py-ja/env/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/miles/webdev/cs50-py-ja/env/lib/python3.6/site-packages/django/db/backends/sqlite3/base.py", line 413, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: no such table: auctions_auctionlisting
Failed to complete cronjob at ('* * * * *', 'auctions.cron.closeoutExpiredListings', '>> /home/miles/webdev/cs50-py-ja/commerce/auctions/cron.log')
Traceback (most recent call last):
  File "/home/miles/webdev/cs50-py-ja/env/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/miles/webdev/cs50-py-ja/env/lib/python3.6/site-packages/django/db/backends/sqlite3/base.py", line 413, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: no such table: auctions_auctionlisting

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/miles/webdev/cs50-py-ja/env/lib/python3.6/site-packages/django_crontab/crontab.py", line 145, in run_job
    func(*job_args, **job_kwargs)
  File "/home/miles/webdev/cs50-py-ja/commerce/auctions/cron.py", line 9, in closeoutExpiredListings
    for listing in exp_listings:
  File "/home/miles/webdev/cs50-py-ja/env/lib/python3.6/site-packages/django/db/models/query.py", line 287, in __iter__
    self._fetch_all()
  File "/home/miles/webdev/cs50-py-ja/env/lib/python3.6/site-packages/django/db/models/query.py", line 1303, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/home/miles/webdev/cs50-py-ja/env/lib/python3.6/site-packages/django/db/models/query.py", line 53, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/home/miles/webdev/cs50-py-ja/env/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1156, in execute_sql
    cursor.execute(sql, params)
  File "/home/miles/webdev/cs50-py-ja/env/lib/python3.6/site-packages/django/db/backends/utils.py", line 98, in execute
    return super().execute(sql, params)
  File "/home/miles/webdev/cs50-py-ja/env/lib/python3.6/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/miles/webdev/cs50-py-ja/env/lib/python3.6/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/miles/webdev/cs50-py-ja/env/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/miles/webdev/cs50-py-ja/env/lib/python3.6/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/miles/webdev/cs50-py-ja/env/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/miles/webdev/cs50-py-ja/env/lib/python3.6/site-packages/django/db/backends/sqlite3/base.py", line 413, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: no such table: auctions_auctionlisting
Failed to complete cronjob at ('* * * * *', 'auctions.cron.closeoutExpiredListings', '>> /home/miles/webdev/cs50-py-ja/commerce/auctions/cron.log')
Traceback (most recent call last):
  File "/home/miles/webdev/cs50-py-ja/env/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/miles/webdev/cs50-py-ja/env/lib/python3.6/site-packages/django/db/backends/sqlite3/base.py", line 413, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: no such table: auctions_auctionlisting

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/miles/webdev/cs50-py-ja/env/lib/python3.6/site-packages/django_crontab/crontab.py", line 145, in run_job
    func(*job_args, **job_kwargs)
  File "/home/miles/webdev/cs50-py-ja/commerce/auctions/cron.py", line 9, in closeoutExpiredListings
    for listing in exp_listings:
  File "/home/miles/webdev/cs50-py-ja/env/lib/python3.6/site-packages/django/db/models/query.py", line 287, in __iter__
    self._fetch_all()
  File "/home/miles/webdev/cs50-py-ja/env/lib/python3.6/site-packages/django/db/models/query.py", line 1303, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/home/miles/webdev/cs50-py-ja/env/lib/python3.6/site-packages/django/db/models/query.py", line 53, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/home/miles/webdev/cs50-py-ja/env/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1156, in execute_sql
    cursor.execute(sql, params)
  File "/home/miles/webdev/cs50-py-ja/env/lib/python3.6/site-packages/django/db/backends/utils.py", line 98, in execute
    return super().execute(sql, params)
  File "/home/miles/webdev/cs50-py-ja/env/lib/python3.6/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/miles/webdev/cs50-py-ja/env/lib/python3.6/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/miles/webdev/cs50-py-ja/env/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/miles/webdev/cs50-py-ja/env/lib/python3.6/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/miles/webdev/cs50-py-ja/env/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/miles/webdev/cs50-py-ja/env/lib/python3.6/site-packages/django/db/backends/sqlite3/base.py", line 413, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: no such table: auctions_auctionlisting
Traceback (most recent call last):
  File "/home/miles/webdev/cs50-py-ja/commerce/manage.py", line 21, in <module>
    main()
  File "/home/miles/webdev/cs50-py-ja/commerce/manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/home/miles/webdev/cs50-py-ja/env/lib/python3.6/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/home/miles/webdev/cs50-py-ja/env/lib/python3.6/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/miles/webdev/cs50-py-ja/env/lib/python3.6/site-packages/django/core/management/base.py", line 330, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/miles/webdev/cs50-py-ja/env/lib/python3.6/site-packages/django/core/management/base.py", line 368, in execute
    self.check()
  File "/home/miles/webdev/cs50-py-ja/env/lib/python3.6/site-packages/django/core/management/base.py", line 396, in check
    databases=databases,
  File "/home/miles/webdev/cs50-py-ja/env/lib/python3.6/site-packages/django/core/checks/registry.py", line 70, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "/home/miles/webdev/cs50-py-ja/env/lib/python3.6/site-packages/django/core/checks/urls.py", line 40, in check_url_namespaces_unique
    all_namespaces = _load_all_namespaces(resolver)
  File "/home/miles/webdev/cs50-py-ja/env/lib/python3.6/site-packages/django/core/checks/urls.py", line 57, in _load_all_namespaces
    url_patterns = getattr(resolver, 'url_patterns', [])
  File "/home/miles/webdev/cs50-py-ja/env/lib/python3.6/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/miles/webdev/cs50-py-ja/env/lib/python3.6/site-packages/django/urls/resolvers.py", line 589, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/miles/webdev/cs50-py-ja/env/lib/python3.6/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/miles/webdev/cs50-py-ja/env/lib/python3.6/site-packages/django/urls/resolvers.py", line 582, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/miles/webdev/cs50-py-ja/commerce/commerce/urls.py", line 21, in <module>
    path("", include("auctions.urls"))
  File "/home/miles/webdev/cs50-py-ja/env/lib/python3.6/site-packages/django/urls/conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/miles/webdev/cs50-py-ja/commerce/auctions/urls.py", line 3, in <module>
    from . import views
  File "/home/miles/webdev/cs50-py-ja/commerce/auctions/views.py", line 9, in <module>
    from helpers import getFullText
ModuleNotFoundError: No module named 'helpers'
Traceback (most recent call last):
  File "/home/miles/webdev/cs50-py-ja/commerce/manage.py", line 21, in <module>
    main()
  File "/home/miles/webdev/cs50-py-ja/commerce/manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/home/miles/webdev/cs50-py-ja/env/lib/python3.6/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/home/miles/webdev/cs50-py-ja/env/lib/python3.6/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/miles/webdev/cs50-py-ja/env/lib/python3.6/site-packages/django/core/management/base.py", line 330, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/miles/webdev/cs50-py-ja/env/lib/python3.6/site-packages/django/core/management/base.py", line 368, in execute
    self.check()
  File "/home/miles/webdev/cs50-py-ja/env/lib/python3.6/site-packages/django/core/management/base.py", line 396, in check
    databases=databases,
  File "/home/miles/webdev/cs50-py-ja/env/lib/python3.6/site-packages/django/core/checks/registry.py", line 70, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "/home/miles/webdev/cs50-py-ja/env/lib/python3.6/site-packages/django/core/checks/urls.py", line 40, in check_url_namespaces_unique
    all_namespaces = _load_all_namespaces(resolver)
  File "/home/miles/webdev/cs50-py-ja/env/lib/python3.6/site-packages/django/core/checks/urls.py", line 57, in _load_all_namespaces
    url_patterns = getattr(resolver, 'url_patterns', [])
  File "/home/miles/webdev/cs50-py-ja/env/lib/python3.6/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/miles/webdev/cs50-py-ja/env/lib/python3.6/site-packages/django/urls/resolvers.py", line 589, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/miles/webdev/cs50-py-ja/env/lib/python3.6/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/miles/webdev/cs50-py-ja/env/lib/python3.6/site-packages/django/urls/resolvers.py", line 582, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/miles/webdev/cs50-py-ja/commerce/commerce/urls.py", line 21, in <module>
    path("", include("auctions.urls"))
  File "/home/miles/webdev/cs50-py-ja/env/lib/python3.6/site-packages/django/urls/conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/miles/webdev/cs50-py-ja/commerce/auctions/urls.py", line 3, in <module>
    from . import views
  File "/home/miles/webdev/cs50-py-ja/commerce/auctions/views.py", line 9, in <module>
    from .helpers import getFullText
  File "/home/miles/webdev/cs50-py-ja/commerce/auctions/helpers.py", line 11
    elif:
        ^
SyntaxError: invalid syntax
Traceback (most recent call last):
  File "/home/miles/webdev/cs50-py-ja/commerce/manage.py", line 21, in <module>
    main()
  File "/home/miles/webdev/cs50-py-ja/commerce/manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/home/miles/webdev/cs50-py-ja/env/lib/python3.6/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/home/miles/webdev/cs50-py-ja/env/lib/python3.6/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/miles/webdev/cs50-py-ja/env/lib/python3.6/site-packages/django/core/management/base.py", line 330, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/miles/webdev/cs50-py-ja/env/lib/python3.6/site-packages/django/core/management/base.py", line 368, in execute
    self.check()
  File "/home/miles/webdev/cs50-py-ja/env/lib/python3.6/site-packages/django/core/management/base.py", line 396, in check
    databases=databases,
  File "/home/miles/webdev/cs50-py-ja/env/lib/python3.6/site-packages/django/core/checks/registry.py", line 70, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "/home/miles/webdev/cs50-py-ja/env/lib/python3.6/site-packages/django/core/checks/urls.py", line 40, in check_url_namespaces_unique
    all_namespaces = _load_all_namespaces(resolver)
  File "/home/miles/webdev/cs50-py-ja/env/lib/python3.6/site-packages/django/core/checks/urls.py", line 57, in _load_all_namespaces
    url_patterns = getattr(resolver, 'url_patterns', [])
  File "/home/miles/webdev/cs50-py-ja/env/lib/python3.6/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/miles/webdev/cs50-py-ja/env/lib/python3.6/site-packages/django/urls/resolvers.py", line 589, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/miles/webdev/cs50-py-ja/env/lib/python3.6/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/miles/webdev/cs50-py-ja/env/lib/python3.6/site-packages/django/urls/resolvers.py", line 582, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/miles/webdev/cs50-py-ja/commerce/commerce/urls.py", line 21, in <module>
    path("", include("auctions.urls"))
  File "/home/miles/webdev/cs50-py-ja/env/lib/python3.6/site-packages/django/urls/conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/miles/webdev/cs50-py-ja/commerce/auctions/urls.py", line 3, in <module>
    from . import views
  File "/home/miles/webdev/cs50-py-ja/commerce/auctions/views.py", line 9, in <module>
    from .helpers import getFullText
  File "/home/miles/webdev/cs50-py-ja/commerce/auctions/helpers.py", line 11
    elif:
        ^
SyntaxError: invalid syntax
Traceback (most recent call last):
  File "/home/miles/webdev/cs50-py-ja/commerce/manage.py", line 21, in <module>
    main()
  File "/home/miles/webdev/cs50-py-ja/commerce/manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/home/miles/webdev/cs50-py-ja/env/lib/python3.6/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/home/miles/webdev/cs50-py-ja/env/lib/python3.6/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/miles/webdev/cs50-py-ja/env/lib/python3.6/site-packages/django/core/management/base.py", line 330, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/miles/webdev/cs50-py-ja/env/lib/python3.6/site-packages/django/core/management/base.py", line 368, in execute
    self.check()
  File "/home/miles/webdev/cs50-py-ja/env/lib/python3.6/site-packages/django/core/management/base.py", line 396, in check
    databases=databases,
  File "/home/miles/webdev/cs50-py-ja/env/lib/python3.6/site-packages/django/core/checks/registry.py", line 70, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "/home/miles/webdev/cs50-py-ja/env/lib/python3.6/site-packages/django/core/checks/urls.py", line 40, in check_url_namespaces_unique
    all_namespaces = _load_all_namespaces(resolver)
  File "/home/miles/webdev/cs50-py-ja/env/lib/python3.6/site-packages/django/core/checks/urls.py", line 57, in _load_all_namespaces
    url_patterns = getattr(resolver, 'url_patterns', [])
  File "/home/miles/webdev/cs50-py-ja/env/lib/python3.6/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/miles/webdev/cs50-py-ja/env/lib/python3.6/site-packages/django/urls/resolvers.py", line 589, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/miles/webdev/cs50-py-ja/env/lib/python3.6/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/miles/webdev/cs50-py-ja/env/lib/python3.6/site-packages/django/urls/resolvers.py", line 582, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/miles/webdev/cs50-py-ja/commerce/commerce/urls.py", line 21, in <module>
    path("", include("auctions.urls"))
  File "/home/miles/webdev/cs50-py-ja/env/lib/python3.6/site-packages/django/urls/conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/miles/webdev/cs50-py-ja/commerce/auctions/urls.py", line 3, in <module>
    from . import views
  File "/home/miles/webdev/cs50-py-ja/commerce/auctions/views.py", line 9, in <module>
    from .helpers import getFullText
  File "/home/miles/webdev/cs50-py-ja/commerce/auctions/helpers.py", line 29
    else:
        ^
IndentationError: unindent does not match any outer indentation level
Traceback (most recent call last):
  File "/home/miles/webdev/cs50-py-ja/commerce/manage.py", line 21, in <module>
    main()
  File "/home/miles/webdev/cs50-py-ja/commerce/manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/home/miles/webdev/cs50-py-ja/env/lib/python3.6/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/home/miles/webdev/cs50-py-ja/env/lib/python3.6/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/miles/webdev/cs50-py-ja/env/lib/python3.6/site-packages/django/core/management/base.py", line 330, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/miles/webdev/cs50-py-ja/env/lib/python3.6/site-packages/django/core/management/base.py", line 368, in execute
    self.check()
  File "/home/miles/webdev/cs50-py-ja/env/lib/python3.6/site-packages/django/core/management/base.py", line 396, in check
    databases=databases,
  File "/home/miles/webdev/cs50-py-ja/env/lib/python3.6/site-packages/django/core/checks/registry.py", line 70, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "/home/miles/webdev/cs50-py-ja/env/lib/python3.6/site-packages/django/core/checks/urls.py", line 40, in check_url_namespaces_unique
    all_namespaces = _load_all_namespaces(resolver)
  File "/home/miles/webdev/cs50-py-ja/env/lib/python3.6/site-packages/django/core/checks/urls.py", line 57, in _load_all_namespaces
    url_patterns = getattr(resolver, 'url_patterns', [])
  File "/home/miles/webdev/cs50-py-ja/env/lib/python3.6/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/miles/webdev/cs50-py-ja/env/lib/python3.6/site-packages/django/urls/resolvers.py", line 589, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/miles/webdev/cs50-py-ja/env/lib/python3.6/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/miles/webdev/cs50-py-ja/env/lib/python3.6/site-packages/django/urls/resolvers.py", line 582, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/miles/webdev/cs50-py-ja/commerce/commerce/urls.py", line 21, in <module>
    path("", include("auctions.urls"))
  File "/home/miles/webdev/cs50-py-ja/env/lib/python3.6/site-packages/django/urls/conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/miles/webdev/cs50-py-ja/commerce/auctions/urls.py", line 3, in <module>
    from . import views
  File "/home/miles/webdev/cs50-py-ja/commerce/auctions/views.py", line 9, in <module>
    from .helpers import getFullText
  File "/home/miles/webdev/cs50-py-ja/commerce/auctions/helpers.py", line 29
    else:
        ^
IndentationError: unindent does not match any outer indentation level
Traceback (most recent call last):
  File "/home/miles/webdev/cs50-py-ja/commerce/manage.py", line 21, in <module>
    main()
  File "/home/miles/webdev/cs50-py-ja/commerce/manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/home/miles/webdev/cs50-py-ja/env/lib/python3.6/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/home/miles/webdev/cs50-py-ja/env/lib/python3.6/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/miles/webdev/cs50-py-ja/env/lib/python3.6/site-packages/django/core/management/base.py", line 330, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/miles/webdev/cs50-py-ja/env/lib/python3.6/site-packages/django/core/management/base.py", line 368, in execute
    self.check()
  File "/home/miles/webdev/cs50-py-ja/env/lib/python3.6/site-packages/django/core/management/base.py", line 396, in check
    databases=databases,
  File "/home/miles/webdev/cs50-py-ja/env/lib/python3.6/site-packages/django/core/checks/registry.py", line 70, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "/home/miles/webdev/cs50-py-ja/env/lib/python3.6/site-packages/django/core/checks/urls.py", line 40, in check_url_namespaces_unique
    all_namespaces = _load_all_namespaces(resolver)
  File "/home/miles/webdev/cs50-py-ja/env/lib/python3.6/site-packages/django/core/checks/urls.py", line 57, in _load_all_namespaces
    url_patterns = getattr(resolver, 'url_patterns', [])
  File "/home/miles/webdev/cs50-py-ja/env/lib/python3.6/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/miles/webdev/cs50-py-ja/env/lib/python3.6/site-packages/django/urls/resolvers.py", line 589, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/miles/webdev/cs50-py-ja/env/lib/python3.6/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/miles/webdev/cs50-py-ja/env/lib/python3.6/site-packages/django/urls/resolvers.py", line 582, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/miles/webdev/cs50-py-ja/commerce/commerce/urls.py", line 21, in <module>
    path("", include("auctions.urls"))
  File "/home/miles/webdev/cs50-py-ja/env/lib/python3.6/site-packages/django/urls/conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/miles/webdev/cs50-py-ja/commerce/auctions/urls.py", line 3, in <module>
    from . import views
  File "/home/miles/webdev/cs50-py-ja/commerce/auctions/views.py", line 9, in <module>
    from .helpers import getFullText
  File "/home/miles/webdev/cs50-py-ja/commerce/auctions/helpers.py", line 29
    else:
        ^
IndentationError: unindent does not match any outer indentation level
Traceback (most recent call last):
  File "/home/miles/webdev/cs50-py-ja/commerce/manage.py", line 21, in <module>
    main()
  File "/home/miles/webdev/cs50-py-ja/commerce/manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/home/miles/webdev/cs50-py-ja/env/lib/python3.6/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/home/miles/webdev/cs50-py-ja/env/lib/python3.6/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/miles/webdev/cs50-py-ja/env/lib/python3.6/site-packages/django/core/management/base.py", line 330, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/miles/webdev/cs50-py-ja/env/lib/python3.6/site-packages/django/core/management/base.py", line 368, in execute
    self.check()
  File "/home/miles/webdev/cs50-py-ja/env/lib/python3.6/site-packages/django/core/management/base.py", line 396, in check
    databases=databases,
  File "/home/miles/webdev/cs50-py-ja/env/lib/python3.6/site-packages/django/core/checks/registry.py", line 70, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "/home/miles/webdev/cs50-py-ja/env/lib/python3.6/site-packages/django/core/checks/urls.py", line 40, in check_url_namespaces_unique
    all_namespaces = _load_all_namespaces(resolver)
  File "/home/miles/webdev/cs50-py-ja/env/lib/python3.6/site-packages/django/core/checks/urls.py", line 57, in _load_all_namespaces
    url_patterns = getattr(resolver, 'url_patterns', [])
  File "/home/miles/webdev/cs50-py-ja/env/lib/python3.6/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/miles/webdev/cs50-py-ja/env/lib/python3.6/site-packages/django/urls/resolvers.py", line 589, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/miles/webdev/cs50-py-ja/env/lib/python3.6/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/miles/webdev/cs50-py-ja/env/lib/python3.6/site-packages/django/urls/resolvers.py", line 582, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/miles/webdev/cs50-py-ja/commerce/commerce/urls.py", line 21, in <module>
    path("", include("auctions.urls"))
  File "/home/miles/webdev/cs50-py-ja/env/lib/python3.6/site-packages/django/urls/conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/miles/webdev/cs50-py-ja/commerce/auctions/urls.py", line 3, in <module>
    from . import views
  File "/home/miles/webdev/cs50-py-ja/commerce/auctions/views.py", line 9, in <module>
    from .helpers import getFullText
  File "/home/miles/webdev/cs50-py-ja/commerce/auctions/helpers.py", line 29
    else:
        ^
IndentationError: unindent does not match any outer indentation level
Traceback (most recent call last):
  File "/home/miles/webdev/cs50-py-ja/commerce/manage.py", line 21, in <module>
    main()
  File "/home/miles/webdev/cs50-py-ja/commerce/manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/home/miles/webdev/cs50-py-ja/env/lib/python3.6/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/home/miles/webdev/cs50-py-ja/env/lib/python3.6/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/miles/webdev/cs50-py-ja/env/lib/python3.6/site-packages/django/core/management/base.py", line 330, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/miles/webdev/cs50-py-ja/env/lib/python3.6/site-packages/django/core/management/base.py", line 368, in execute
    self.check()
  File "/home/miles/webdev/cs50-py-ja/env/lib/python3.6/site-packages/django/core/management/base.py", line 396, in check
    databases=databases,
  File "/home/miles/webdev/cs50-py-ja/env/lib/python3.6/site-packages/django/core/checks/registry.py", line 70, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "/home/miles/webdev/cs50-py-ja/env/lib/python3.6/site-packages/django/core/checks/urls.py", line 40, in check_url_namespaces_unique
    all_namespaces = _load_all_namespaces(resolver)
  File "/home/miles/webdev/cs50-py-ja/env/lib/python3.6/site-packages/django/core/checks/urls.py", line 57, in _load_all_namespaces
    url_patterns = getattr(resolver, 'url_patterns', [])
  File "/home/miles/webdev/cs50-py-ja/env/lib/python3.6/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/miles/webdev/cs50-py-ja/env/lib/python3.6/site-packages/django/urls/resolvers.py", line 589, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/miles/webdev/cs50-py-ja/env/lib/python3.6/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/miles/webdev/cs50-py-ja/env/lib/python3.6/site-packages/django/urls/resolvers.py", line 582, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/miles/webdev/cs50-py-ja/commerce/commerce/urls.py", line 21, in <module>
    path("", include("auctions.urls"))
  File "/home/miles/webdev/cs50-py-ja/env/lib/python3.6/site-packages/django/urls/conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/miles/webdev/cs50-py-ja/commerce/auctions/urls.py", line 3, in <module>
    from . import views
  File "/home/miles/webdev/cs50-py-ja/commerce/auctions/views.py", line 9, in <module>
    from .helpers import getFullText
  File "/home/miles/webdev/cs50-py-ja/commerce/auctions/helpers.py", line 28
    else:
        ^
IndentationError: unindent does not match any outer indentation level
Traceback (most recent call last):
  File "/home/miles/webdev/cs50-py-ja/commerce/manage.py", line 21, in <module>
    main()
  File "/home/miles/webdev/cs50-py-ja/commerce/manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/home/miles/webdev/cs50-py-ja/env/lib/python3.6/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/home/miles/webdev/cs50-py-ja/env/lib/python3.6/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/miles/webdev/cs50-py-ja/env/lib/python3.6/site-packages/django/core/management/base.py", line 330, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/miles/webdev/cs50-py-ja/env/lib/python3.6/site-packages/django/core/management/base.py", line 368, in execute
    self.check()
  File "/home/miles/webdev/cs50-py-ja/env/lib/python3.6/site-packages/django/core/management/base.py", line 396, in check
    databases=databases,
  File "/home/miles/webdev/cs50-py-ja/env/lib/python3.6/site-packages/django/core/checks/registry.py", line 70, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "/home/miles/webdev/cs50-py-ja/env/lib/python3.6/site-packages/django/core/checks/urls.py", line 40, in check_url_namespaces_unique
    all_namespaces = _load_all_namespaces(resolver)
  File "/home/miles/webdev/cs50-py-ja/env/lib/python3.6/site-packages/django/core/checks/urls.py", line 57, in _load_all_namespaces
    url_patterns = getattr(resolver, 'url_patterns', [])
  File "/home/miles/webdev/cs50-py-ja/env/lib/python3.6/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/miles/webdev/cs50-py-ja/env/lib/python3.6/site-packages/django/urls/resolvers.py", line 589, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/miles/webdev/cs50-py-ja/env/lib/python3.6/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/miles/webdev/cs50-py-ja/env/lib/python3.6/site-packages/django/urls/resolvers.py", line 582, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/miles/webdev/cs50-py-ja/commerce/commerce/urls.py", line 21, in <module>
    path("", include("auctions.urls"))
  File "/home/miles/webdev/cs50-py-ja/env/lib/python3.6/site-packages/django/urls/conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/miles/webdev/cs50-py-ja/commerce/auctions/urls.py", line 3, in <module>
    from . import views
  File "/home/miles/webdev/cs50-py-ja/commerce/auctions/views.py", line 9, in <module>
    from .helpers import getFullText
  File "/home/miles/webdev/cs50-py-ja/commerce/auctions/helpers.py", line 28
    else:
        ^
IndentationError: unindent does not match any outer indentation level
Traceback (most recent call last):
  File "/home/miles/webdev/cs50-py-ja/commerce/manage.py", line 21, in <module>
    main()
  File "/home/miles/webdev/cs50-py-ja/commerce/manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/home/miles/webdev/cs50-py-ja/env/lib/python3.6/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/home/miles/webdev/cs50-py-ja/env/lib/python3.6/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/miles/webdev/cs50-py-ja/env/lib/python3.6/site-packages/django/core/management/base.py", line 330, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/miles/webdev/cs50-py-ja/env/lib/python3.6/site-packages/django/core/management/base.py", line 368, in execute
    self.check()
  File "/home/miles/webdev/cs50-py-ja/env/lib/python3.6/site-packages/django/core/management/base.py", line 396, in check
    databases=databases,
  File "/home/miles/webdev/cs50-py-ja/env/lib/python3.6/site-packages/django/core/checks/registry.py", line 70, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "/home/miles/webdev/cs50-py-ja/env/lib/python3.6/site-packages/django/core/checks/urls.py", line 40, in check_url_namespaces_unique
    all_namespaces = _load_all_namespaces(resolver)
  File "/home/miles/webdev/cs50-py-ja/env/lib/python3.6/site-packages/django/core/checks/urls.py", line 57, in _load_all_namespaces
    url_patterns = getattr(resolver, 'url_patterns', [])
  File "/home/miles/webdev/cs50-py-ja/env/lib/python3.6/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/miles/webdev/cs50-py-ja/env/lib/python3.6/site-packages/django/urls/resolvers.py", line 589, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/miles/webdev/cs50-py-ja/env/lib/python3.6/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/miles/webdev/cs50-py-ja/env/lib/python3.6/site-packages/django/urls/resolvers.py", line 582, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/miles/webdev/cs50-py-ja/commerce/commerce/urls.py", line 21, in <module>
    path("", include("auctions.urls"))
  File "/home/miles/webdev/cs50-py-ja/env/lib/python3.6/site-packages/django/urls/conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/miles/webdev/cs50-py-ja/commerce/auctions/urls.py", line 3, in <module>
    from . import views
  File "/home/miles/webdev/cs50-py-ja/commerce/auctions/views.py", line 9, in <module>
    from .helpers import getFullText
  File "/home/miles/webdev/cs50-py-ja/commerce/auctions/helpers.py", line 31
    else:
        ^
IndentationError: unindent does not match any outer indentation level
Traceback (most recent call last):
  File "/home/miles/webdev/cs50-py-ja/commerce/manage.py", line 21, in <module>
    main()
  File "/home/miles/webdev/cs50-py-ja/commerce/manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/home/miles/webdev/cs50-py-ja/env/lib/python3.6/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/home/miles/webdev/cs50-py-ja/env/lib/python3.6/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/miles/webdev/cs50-py-ja/env/lib/python3.6/site-packages/django/core/management/base.py", line 330, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/miles/webdev/cs50-py-ja/env/lib/python3.6/site-packages/django/core/management/base.py", line 368, in execute
    self.check()
  File "/home/miles/webdev/cs50-py-ja/env/lib/python3.6/site-packages/django/core/management/base.py", line 396, in check
    databases=databases,
  File "/home/miles/webdev/cs50-py-ja/env/lib/python3.6/site-packages/django/core/checks/registry.py", line 70, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "/home/miles/webdev/cs50-py-ja/env/lib/python3.6/site-packages/django/core/checks/urls.py", line 40, in check_url_namespaces_unique
    all_namespaces = _load_all_namespaces(resolver)
  File "/home/miles/webdev/cs50-py-ja/env/lib/python3.6/site-packages/django/core/checks/urls.py", line 57, in _load_all_namespaces
    url_patterns = getattr(resolver, 'url_patterns', [])
  File "/home/miles/webdev/cs50-py-ja/env/lib/python3.6/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/miles/webdev/cs50-py-ja/env/lib/python3.6/site-packages/django/urls/resolvers.py", line 589, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/miles/webdev/cs50-py-ja/env/lib/python3.6/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/miles/webdev/cs50-py-ja/env/lib/python3.6/site-packages/django/urls/resolvers.py", line 582, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/miles/webdev/cs50-py-ja/commerce/commerce/urls.py", line 21, in <module>
    path("", include("auctions.urls"))
  File "/home/miles/webdev/cs50-py-ja/env/lib/python3.6/site-packages/django/urls/conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/miles/webdev/cs50-py-ja/commerce/auctions/urls.py", line 3, in <module>
    from . import views
  File "/home/miles/webdev/cs50-py-ja/commerce/auctions/views.py", line 9, in <module>
    from .helpers import getFullText
  File "/home/miles/webdev/cs50-py-ja/commerce/auctions/helpers.py", line 30
    else:
        ^
IndentationError: unindent does not match any outer indentation level
Traceback (most recent call last):
  File "/home/miles/webdev/cs50-py-ja/commerce/manage.py", line 21, in <module>
    main()
  File "/home/miles/webdev/cs50-py-ja/commerce/manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/home/miles/webdev/cs50-py-ja/env/lib/python3.6/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/home/miles/webdev/cs50-py-ja/env/lib/python3.6/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/miles/webdev/cs50-py-ja/env/lib/python3.6/site-packages/django/core/management/base.py", line 330, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/miles/webdev/cs50-py-ja/env/lib/python3.6/site-packages/django/core/management/base.py", line 368, in execute
    self.check()
  File "/home/miles/webdev/cs50-py-ja/env/lib/python3.6/site-packages/django/core/management/base.py", line 396, in check
    databases=databases,
  File "/home/miles/webdev/cs50-py-ja/env/lib/python3.6/site-packages/django/core/checks/registry.py", line 70, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "/home/miles/webdev/cs50-py-ja/env/lib/python3.6/site-packages/django/core/checks/urls.py", line 40, in check_url_namespaces_unique
    all_namespaces = _load_all_namespaces(resolver)
  File "/home/miles/webdev/cs50-py-ja/env/lib/python3.6/site-packages/django/core/checks/urls.py", line 57, in _load_all_namespaces
    url_patterns = getattr(resolver, 'url_patterns', [])
  File "/home/miles/webdev/cs50-py-ja/env/lib/python3.6/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/miles/webdev/cs50-py-ja/env/lib/python3.6/site-packages/django/urls/resolvers.py", line 589, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/miles/webdev/cs50-py-ja/env/lib/python3.6/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/miles/webdev/cs50-py-ja/env/lib/python3.6/site-packages/django/urls/resolvers.py", line 582, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/miles/webdev/cs50-py-ja/commerce/commerce/urls.py", line 21, in <module>
    path("", include("auctions.urls"))
  File "/home/miles/webdev/cs50-py-ja/env/lib/python3.6/site-packages/django/urls/conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/miles/webdev/cs50-py-ja/commerce/auctions/urls.py", line 3, in <module>
    from . import views
  File "/home/miles/webdev/cs50-py-ja/commerce/auctions/views.py", line 9, in <module>
    from .helpers import getFullText
  File "/home/miles/webdev/cs50-py-ja/commerce/auctions/helpers.py", line 27
    if Bid.objects.filter(listing=listing.id, is_active=True).exists():
    ^
IndentationError: unexpected indent
